comment:
  layout: "reach, diff, flags, files"
  require_changes: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: proj-
        type: project
        target: auto
        threshold: 5%
      - name_prefix: patch-
        type: patch
        target: auto
        threshold: 5%
  individual_flags:
    - name: taro-cli
      paths:
        - packages/taro-cli/
    - name: taro-components
      paths:
        - packages/taro-components/
    - name: rest
      paths:
        - packages/
