packages:
  - 'packages/**'
  - 'fixtures/*'
  - '!packages/taro-cli/templates/**'
  - '!packages/taro-cli/tests/fixtures/**'
  - '!**/__tests__/**'
  - '!**/dist/**'
  - '!**/harmony_project/**'
  - 'npm/darwin-arm64'
  - 'crates/native_binding'
