type ComponentAttributeMap = Record<string, string>;
type ComponentMap = Record<string, ComponentAttributeMap>;

const TRUE = 'true';
const FALSE = 'false';
const EMPTY = '';
const ZERO = '0';
const OBJECT = '{}';
const ARRAY = '[]';

export const components: ComponentMap = {
  // 基础调整
  Progress: {
    'border-radius': ZERO,
    'font-size': '16',
    duration: '30',
    bindActiveEnd: EMPTY,
  },
  RichText: {
    space: EMPTY,
    'user-select': FALSE,
    mode: "'default'",
  },
  Text: {
    'user-select': FALSE,
    overflow: 'visible',
    'max-lines': '',
  },
  Map: {
    polygons: ARRAY,
    subkey: EMPTY,
    rotate: ZERO,
    skew: ZERO,
    'max-scale': '20',
    'min-scale': '3',
    'enable-3D': FALSE,
    'show-compass': FALSE,
    'show-scale': FALSE,
    'enable-overlooking': FALSE,
    'enable-auto-max-overlooking': FALSE,
    'enable-zoom': TRUE,
    'enable-scroll': TRUE,
    'enable-rotate': FALSE,
    'enable-satellite': FALSE,
    'enable-traffic': FALSE,
    'enable-poi': TRUE,
    'enable-building': TRUE,
    setting: OBJECT,
    bindLabelTap: EMPTY,
    bindRegionChange: EMPTY,
    bindPoiTap: EMPTY,
    bindPolylineTap: EMPTY,
    bindAbilitySuccess: EMPTY,
    bindAbilityFailed: EMPTY,
    bindAuthSuccess: EMPTY,
    bindInterpolatePoint: EMPTY,
    bindError: EMPTY,
    bindAnchorPointTap: EMPTY,
  },
  Button: {
    lang: 'en',
    'session-from': EMPTY,
    'send-message-title': EMPTY,
    'send-message-path': EMPTY,
    'send-message-img': EMPTY,
    'app-parameter': EMPTY,
    'show-message-card': FALSE,
    'business-id': EMPTY,
    bindGetUserInfo: EMPTY,
    bindContact: EMPTY,
    bindGetPhoneNumber: EMPTY,
    bindGetRealTimePhoneNumber: EMPTY,
    bindChooseAvatar: EMPTY,
    bindError: EMPTY,
    bindOpenSetting: EMPTY,
    bindLaunchApp: EMPTY,
    bindAgreePrivacyAuthorization: EMPTY,
  },
  Form: {
    'report-submit-timeout': ZERO,
  },
  Input: {
    'always-embed': FALSE,
    'adjust-position': TRUE,
    'hold-keyboard': FALSE,
    'safe-password-cert-path': '',
    'safe-password-length': '',
    'safe-password-time-stamp': '',
    'safe-password-nonce': '',
    'safe-password-salt': '',
    'safe-password-custom-hash': '',
    'auto-fill': EMPTY,
    'cursor-color': '',
    bindKeyboardHeightChange: EMPTY,
    bindNicknameReview: EMPTY,
    bindSelectionChange: EMPTY,
    bindKeyboardCompositionStart: EMPTY,
    bindKeyboardCompositionUpdate: EMPTY,
    bindKeyboardCompositionEnd: EMPTY,
  },
  Picker: {
    'header-text': EMPTY,
    level: 'region',
  },
  PickerView: {
    'immediate-change': FALSE,
    bindPickStart: EMPTY,
    bindPickEnd: EMPTY,
  },
  Slider: {
    color: "'#e9e9e9'",
    'selected-color': "'#1aad19'",
  },
  Textarea: {
    'show-confirm-bar': TRUE,
    'adjust-position': TRUE,
    'hold-keyboard': FALSE,
    'disable-default-padding': FALSE,
    'confirm-type': "'return'",
    'confirm-hold': FALSE,
    'adjust-keyboard-to': "'cursor'",
    bindKeyboardHeightChange: EMPTY,
    bindSelectionChange: EMPTY,
    bindKeyboardCompositionStart: EMPTY,
    bindKeyboardCompositionUpdate: EMPTY,
    bindKeyboardCompositionEnd: EMPTY,
  },
  ScrollView: {
    'enable-flex': FALSE,
    'scroll-anchoring': FALSE,
    enhanced: FALSE,
    'using-sticky': FALSE,
    'paging-enabled': FALSE,
    'enable-passive': FALSE,
    'refresher-enabled': FALSE,
    'refresher-threshold': '45',
    'refresher-default-style': "'black'",
    'refresher-background': "'#FFF'",
    'refresher-triggered': FALSE,
    bounces: TRUE,
    'show-scrollbar': TRUE,
    'fast-deceleration': FALSE,
    type: "'list'",
    'associative-container': "''",
    reverse: FALSE,
    clip: TRUE,
    'enable-back-to-top': FALSE,
    'cache-extent': EMPTY,
    'min-drag-distance': '18',
    'scroll-into-view-within-extent': FALSE,
    'scroll-into-view-alignment': "'start'",
    padding: ARRAY,
    'refresher-two-level-enabled': FALSE,
    'refresher-two-level-triggered': FALSE,
    'refresher-two-level-threshold': '150',
    'refresher-two-level-close-threshold': '80',
    'refresher-two-level-scroll-enabled': FALSE,
    'refresher-ballistic-refresh-enabled': FALSE,
    'refresher-two-level-pinned': FALSE,
    bindDragStart: EMPTY,
    bindDragging: EMPTY,
    bindDragEnd: EMPTY,
    bindRefresherPulling: EMPTY,
    bindRefresherRefresh: EMPTY,
    bindRefresherRestore: EMPTY,
    bindRefresherAbort: EMPTY,
    bindScrollStart: EMPTY,
    bindScrollEnd: EMPTY,
    bindRefresherWillRefresh: EMPTY,
    bindRefresherStatusChange: EMPTY,
  },
  StickySection: {
    'push-pinned-header': TRUE,
    padding: ARRAY,
  },
  GridView: {
    type: "'aligned'",
    'cross-axis-count': '2',
    'max-cross-axis-extent': ZERO,
    'main-axis-gap': ZERO,
    'cross-axis-gap': ZERO,
    padding: ARRAY,
  },
  GridBuilder: {
    type: "'aligned'",
    list: ARRAY,
    'cross-axis-count': '2',
    'max-cross-axis-extent': ZERO,
    'main-axis-gap': ZERO,
    'cross-axis-gap': ZERO,
    padding: ARRAY,
    bindItemBuild: EMPTY,
    bindItemDispose: EMPTY,
  },
  ListView: {
    padding: ARRAY,
  },
  ListBuilder: {
    list: ARRAY,
    type: 'static',
    padding: ARRAY,
    'child-count': EMPTY,
    'child-height': EMPTY,
    bindItemBuild: EMPTY,
    bindItemDispose: EMPTY,
  },
  StickyHeader: {
    'offset-top': '0',
    padding: ARRAY,
  },
  Swiper: {
    'snap-to-edge': FALSE,
    'easing-function': "'default'",
    'layout-type': "'normal'",
    'transformer-type': "'scaleAndFade'",
    'indicator-type': "'normal'",
    'indicator-margin': '10',
    'indicator-spacing': '4',
    'indicator-radius': '4',
    'indicator-width': '8',
    'indicator-height': '8',
    'indicator-alignment': "'auto'",
    'indicator-offset': '[0, 0]',
    'scroll-with-animation': TRUE,
    'cache-extent': '0',
  },
  SwiperItem: {
    'skip-hidden-item-layout': FALSE,
  },
  Navigator: {
    target: "'self'",
    'app-id': EMPTY,
    path: EMPTY,
    'extra-data': EMPTY,
    version: "'version'",
  },
  Camera: {
    mode: "'normal'",
    resolution: "'medium'",
    'frame-size': "'medium'",
    bindInitDone: EMPTY,
    bindScanCode: EMPTY,
  },
  Image: {
    webp: FALSE,
    'show-menu-by-longpress': FALSE,
    'fade-in': FALSE,
  },
  LivePlayer: {
    mode: "'live'",
    'sound-mode': "'speaker'",
    'auto-pause-if-navigate': TRUE,
    'auto-pause-if-open-native': TRUE,
    'picture-in-picture-mode': ARRAY,
    'enable-auto-rotation': FALSE,
    'referrer-policy': "'no-referrer'",
    'enable-casting': FALSE,
    bindstatechange: EMPTY,
    bindfullscreenchange: EMPTY,
    bindnetstatus: EMPTY,
    bindAudioVolumeNotify: EMPTY,
    bindEnterPictureInPicture: EMPTY,
    bindLeavePictureInPicture: EMPTY,
    bindCastingUserSelect: EMPTY,
    bindCastingStateChange: EMPTY,
    bindCastingInterrupt: EMPTY,
  },
  Video: {
    title: EMPTY,
    'play-btn-position': "'bottom'",
    'enable-play-gesture': FALSE,
    'auto-pause-if-navigate': TRUE,
    'auto-pause-if-open-native': TRUE,
    'vslide-gesture': FALSE,
    'vslide-gesture-in-fullscreen': TRUE,
    'show-bottom-progress': TRUE,
    'ad-unit-id': EMPTY,
    'poster-for-crawler': EMPTY,
    'show-casting-button': FALSE,
    'picture-in-picture-mode': ARRAY,
    'enable-auto-rotation': FALSE,
    'show-screen-lock-button': FALSE,
    'show-snapshot-button': FALSE,
    'show-background-playback-button': FALSE,
    'background-poster': EMPTY,
    'referrer-policy': "'no-referrer'",
    'is-drm': FALSE,
    'is-live': FALSE,
    'provision-url': EMPTY,
    'certificate-url': EMPTY,
    'license-url': EMPTY,
    'preferred-peak-bit-rate': EMPTY,
    bindProgress: EMPTY,
    bindLoadedMetadata: EMPTY,
    bindControlsToggle: EMPTY,
    bindEnterPictureInPicture: EMPTY,
    bindLeavePictureInPicture: EMPTY,
    bindSeekComplete: EMPTY,
    bindCastingUserSelect: EMPTY,
    bindCastingStateChange: EMPTY,
    bindCastingInterrupt: EMPTY,
    bindAdLoad: EMPTY,
    bindAdError: EMPTY,
    bindAdClose: EMPTY,
    bindAdPlay: EMPTY,
  },
  Canvas: {
    type: EMPTY,
  },
  Ad: {
    'ad-type': "'banner'",
    'ad-theme': "'white'",
  },
  CoverView: {
    'marker-id': EMPTY,
    slot: EMPTY,
  },

  // 扩展组件
  Editor: {
    'read-only': FALSE,
    placeholder: EMPTY,
    'show-img-size': FALSE,
    'show-img-toolbar': FALSE,
    'show-img-resize': FALSE,
    focus: FALSE,
    bindReady: EMPTY,
    bindFocus: EMPTY,
    bindBlur: EMPTY,
    bindInput: EMPTY,
    bindStatusChange: EMPTY,
    name: EMPTY,
  },
  MatchMedia: {
    'min-width': EMPTY,
    'max-width': EMPTY,
    width: EMPTY,
    'min-height': EMPTY,
    'max-height': EMPTY,
    height: EMPTY,
    orientation: EMPTY,
  },
  FunctionalPageNavigator: {
    version: "'release'",
    name: EMPTY,
    args: EMPTY,
    bindSuccess: EMPTY,
    bindFail: EMPTY,
    bindCancel: EMPTY,
  },
  LivePusher: {
    url: EMPTY,
    mode: "'RTC'",
    autopush: FALSE,
    muted: FALSE,
    'enable-camera': TRUE,
    'auto-focus': TRUE,
    orientation: "'vertical'",
    beauty: ZERO,
    whiteness: ZERO,
    aspect: "'9:16'",
    'min-bitrate': '200',
    'max-bitrate': '1000',
    'audio-quality': "'high'",
    'waiting-image': EMPTY,
    'waiting-image-hash': EMPTY,
    zoom: FALSE,
    'device-position': "'front'",
    'background-mute': FALSE,
    mirror: FALSE,
    'remote-mirror': FALSE,
    'local-mirror': FALSE,
    'audio-reverb-type': ZERO,
    'enable-mic': TRUE,
    'enable-agc': FALSE,
    'enable-ans': FALSE,
    'audio-volume-type': "'voicecall'",
    'video-width': '360',
    'video-height': '640',
    'beauty-style': "'smooth'",
    filter: "'standard'",
    'picture-in-picture-mode': ARRAY,
    animation: EMPTY,
    bindStateChange: EMPTY,
    bindNetStatus: EMPTY,
    bindBgmStart: EMPTY,
    bindBgmProgress: EMPTY,
    bindBgmComplete: EMPTY,
    bindAudioVolumeNotify: EMPTY,
  },
  OfficialAccount: {
    bindLoad: EMPTY,
    bindError: EMPTY,
  },
  OpenData: {
    type: EMPTY,
    'open-gid': EMPTY,
    lang: "'en'",
    'default-text': EMPTY,
    'default-avatar': EMPTY,
    bindError: EMPTY,
  },
  NavigationBar: {
    title: EMPTY,
    loading: FALSE,
    'front-color': "'#000000'",
    'background-color': EMPTY,
    'color-animation-duration': ZERO,
    'color-animation-timing-func': "'linear'",
  },
  PageMeta: {
    'background-text-style': EMPTY,
    'background-color': EMPTY,
    'background-color-top': EMPTY,
    'background-color-bottom': EMPTY,
    'root-background-color': EMPTY,
    'scroll-top': "''",
    'scroll-duration': '300',
    'page-style': "''",
    'root-font-size': "''",
    'page-orientation': "''",
    bindResize: EMPTY,
    bindScroll: EMPTY,
    bindScrollDone: EMPTY,
  },
  VoipRoom: {
    openid: EMPTY,
    mode: "'camera'",
    'device-position': "'front'",
    bindError: EMPTY,
  },
  AdCustom: {
    'unit-id': EMPTY,
    'ad-intervals': EMPTY,
    bindLoad: EMPTY,
    bindError: EMPTY,
  },
  PageContainer: {
    show: FALSE,
    duration: '300',
    'z-index': '100',
    overlay: TRUE,
    position: "'bottom'",
    round: FALSE,
    'close-on-slide-down': FALSE,
    'overlay-style': EMPTY,
    'custom-style': EMPTY,
    bindBeforeEnter: EMPTY,
    bindEnter: EMPTY,
    bindAfterEnter: EMPTY,
    bindBeforeLeave: EMPTY,
    bindLeave: EMPTY,
    bindAfterLeave: EMPTY,
    bindClickOverlay: EMPTY,
  },
  ShareElement: {
    mapkey: EMPTY,
    transform: FALSE,
    duration: '300',
    'easing-function': "'ease-out'",
    'transition-on-gesture': FALSE,
    'shuttle-on-push': "'to'",
    'shuttle-on-pop': "'to'",
    'rect-tween-type': "'materialRectArc'",
  },
  KeyboardAccessory: {},
  RootPortal: {
    enable: TRUE,
  },
  ChannelLive: {
    'feed-id': EMPTY,
    'finder-user-name': EMPTY,
  },
  ChannelVideo: {
    'feed-id': EMPTY,
    'finder-user-name': EMPTY,
    'feed-token': EMPTY,
    autoplay: FALSE,
    loop: FALSE,
    muted: FALSE,
    'object-fit': "'contain'",
    bindError: EMPTY,
  },
  Snapshot: {
    mode: "'view'",
  },
  Span: {},
  OpenContainer: {
    transitionType: "'fade'",
    transitionDuration: '300',
    closedColor: "'white'",
    closedElevation: ZERO,
    closeBorderRadius: ZERO,
    middleColor: EMPTY,
    openColor: "'white'",
    openElevation: ZERO,
    openBorderRadius: ZERO,
  },
  DraggableSheet: {
    initialChildSize: '0.5',
    minChildSize: '0.25',
    maxChildSize: '1.0',
    snap: FALSE,
    snapSizes: ARRAY,
  },
  NestedScrollHeader: {},
  NestedScrollBody: {},

  // 手势组件
  DoubleTapGestureHandler: {},
  ForcePressGestureHandler: {},
  HorizontalDragGestureHandler: {},
  LongPressGestureHandler: {},
  PanGestureHandler: {},
  ScaleGestureHandler: {},
  TapGestureHandler: {},
  VerticalDragGestureHandler: {},
};
