// prettier-ignore
/* eslint-disable */
/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

if (platform !== 'darwin' || arch !== 'arm64') {
  throw new Error(`@spcsn/taro-binding currently supports darwin/arm64 only, got ${platform}/${arch}`)
}

localFileExisted = existsSync(join(__dirname, 'taro.darwin-arm64.node'))
try {
  if (localFileExisted) {
    nativeBinding = require('./taro.darwin-arm64.node')
  } else {
    nativeBinding = require('@spcsn/taro-binding-darwin-arm64')
  }
} catch (e) {
  loadError = e
}

if (!nativeBinding) {
  const installHint = [
    `Failed to load @spcsn/taro-binding for ${platform}/${arch}.`,
    'Make sure @spcsn/taro-binding and the matching optional platform package are installed together.',
    'If you are developing locally, run `pnpm run artifacts` before release checks or set BUILD_TARO_FROM_SOURCE=1 to build from source.',
  ].join('\n')

  if (loadError) {
    loadError.message = `${installHint}\n\nOriginal error: ${loadError.message}`
    throw loadError
  }
  throw new Error(installHint)
}

module.exports.default = module.exports = nativeBinding
