name: Node CI
env:
  PUPPETEER_SKIP_DOWNLOAD: 'true'
on:
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - '1.x'
      - '2.x'
      - '3.x'
      - '4.x'
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nodejs-testing:
    name: Testing on Node.js ${{ matrix.node-version }} (${{ matrix.host }})
    strategy:
      matrix:
        node-version: [22.x]
        host: [ubuntu-latest]

    runs-on: ${{ matrix.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
      - name: Install dependencies
        run: pnpm -r install --frozen-lockfile
      - name: Export browser path
        run: echo "PUPPETEER_EXECUTABLE_PATH=$(which chrome)" >> $GITHUB_ENV
      - name: Lint
        run: pnpm lint
      - name: build
        run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: test
        run: pnpm test
      # 以下 coverage 流程通过 artifact 拆分文件作为单独 job 上传时间损耗过长，因此在在 node test 后直接继续执行
      - name: Upload [taro-cli] coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: taro-cli
          files: ./packages/taro-cli/coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload components coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: taro-components
          files: ./packages/taro-components/coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload rest coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
